add modal window Product card and About
Voloshun555/command11 pull request #5
Opened 2023-01-22 23:31 UTC by TatyanaVoloshko

Не разобралась со скриптом, который сделал Игорь. Что бы удобно было смотреть код - отправлю архивы со своими файлами вличку в слаке

2023-01-23 08:40 UTC, HannaKompaniiets requested changes
Написала в slack

2023-01-23 13:30 UTC, Arslan2305 requested changes
написав в слак

2023-01-24 11:11 UTC, HannaKompaniiets approved these changes

2023-01-24 11:12 UTC, Voloshun555 approved these changes

2023-01-24 11:19 UTC, merged